method: ddm
state_dim: 2
obs_dim: 2
in_dim: 1
epoch: 5000
pre_fit_epoch: -1
patience: 5
batch_size: 20
activation: leaky_relu
optimizer: rmsprop
lr: 0.0004689411913634608
v_type: single
scale_f: 0.9130121458298864
scale_g: 1.0
scale_h: 1.0
scale_j: 1.0
scale_L: 1.0
train_valid_ratio: 0.2
data_train: ./dataset/nlink3_100nlink.train
data_test: ''
init_model: studynlink3_100_naive_1/trial0090/model/best.checkpoint
result_path: result_studynlink3_100_naive_1
dissipative_mode: naive
gamma: 2.0
eps_P: 1.0
eps_f: 0.01
eps_g: 0.01
Q:
- -1.0
- 0.0
- 0.0
- 0.0
R:
- 0.0
S:
- 0.5
- 0.0
alpha_f: 0.001
alpha_g: 0.001
alpha_h: 0.0013146322841336687
one_step_loss: false
diag_g: false
diag_j: false
detach_f: false
detach_g: false
detach_h: false
detach_j: false
detach_diff_f: false
detach_diff_g: false
fix_f: false
fix_g: false
fix_h: false
fix_j: false
fix_L: false
with_bn_f: false
with_bn_g: false
with_bn_h: false
with_bn_j: false
with_bn_L: false
without_j: true
identity_h: false
consistency_h: true
weight_decay: 1.0991011254462236e-09
hidden_layer_f:
- 14
- 15
hidden_layer_g:
- 26
- 29
hidden_layer_h: []
hidden_layer_j:
- 32
hidden_layer_L:
- 32
residual_f: false
residual_h: true
residual_coeff_f: -1.0
profile: false
